hjelev/rpi-mqtt-monitor

README.md, src/config.py.example, src/rpi-cpu2mqtt.py
Added ```discovery_messages``` to the script to allow the automatic adding of sensors to HA instead of having to manually define them.
=> Added HA MQTT Discovery functionality

src/rpi-cpu2mqtt.py
=> adding a device details to home assistant discovery message

README.md, install.sh, remote_install.sh, src/config.py.example, src/rpi-cpu2mqtt.py
- add wifi signal quality option (If you are upgrading you'll need to add wifi_signal = True to your config.py )
- fix a bug in auto installer where it would fail if git is not installed
=> add wifi signal

README.md, install.sh, src/config.py.example, src/rpi-cpu2mqtt.py
Add wifi signal in dBm. If you want to measure the wifi signal in dBm set this in your configuration file.
```
wifi_signal = False
wifi_signal_dbm = True
```
=> add wifi signal dBm

src/rpi-cpu2mqtt.py
To allow the use of Statistics and Statistics Graph cards
ref: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
=> Support long term statistics

src/config.py.example
Add configurable settings for QOS and retain flag.
=> Add QOS and retain settings

src/rpi-cpu2mqtt.py
Add support for qos and retain variables from config.py.
=> Support for configurable QOS and retain settings

README.md, src/config.py.example, src/rpi-cpu2mqtt.py
=> Fix a bug in git update sensor

README.md, src/rpi-cpu2mqtt.py
The first supported argument is -d which displays the measured values in cli:
Hostname: ubuntu-pc
CPU Load: 22.2
CPU Temp: 65
Used Space: 11
Voltage: False
CPU Clock Speed: False
Swap: False
Memory: 64
Uptime: 0
Wifi Signal: False
Wifi Signal dBm: False
RPI5 Fan Speed: False
Git Update: on
=> added support for command line arguments 

src/rpi-cpu2mqtt.py
add new command line argument -v
=> -v checks local and remote versions

src/rpi-cpu2mqtt.py
=> Add device class update to binary sensor

src/rpi-cpu2mqtt.py
RPi MQTT Monitor can now subscribe to a mqtt topic and listen for commands
Update is the first command that the script understands and it allows him to remotely update via home assistant.
When there is a new version you'll get a notification in home assistant and option to trigger the update.
To support this new feature the script now uses multi threading, one thread to check and send sensor data and one thread to listen for commands.
=> remote update via home assistant

README.md, src/rpi-cpu2mqtt.py, src/update.py
update was not working properly if config.py didn't have an empty line at the end - this is now fixed.
=> update readme.md and device description displayed in hass

src/config.py.example, src/rpi-cpu2mqtt.py
Use *duration* device class and icon and uom as in other Uptime sensors in HA.
=> Add new sensor for uptime in seconds

src/config.py.example, src/rpi-cpu2mqtt.py
Use `loop_start` / `loop_end` instead of sleeping.
=> Remove sleep time

install.sh, rpi-mqtt-monitor.service, src/rpi-cpu2mqtt.py, src/update.py
If the restart button is not working, make sure that your service file is up to date.
=> Fix update system and restart

src/rpi-cpu2mqtt.py
Use github api to obtain latest release notes and display them in home assistant.
=> add release notes to update message

src/rpi-cpu2mqtt.py
Improve code and threads handling
Display system mac address when --display argument is used - this info will be needed for manual config of wake-on-lan switch with MQTT shutdown
=> Improve code and threads handling

src/rpi-cpu2mqtt.py
This adds a check to the `awk` command that prevents divisions by zero. 
Addresses (parts of) the following issues:
- hjelev/rpi-mqtt-monitor#11
- hjelev/rpi-mqtt-monitor#91
Tested on Alpine 3.19.1 on a Raspberry Pi 5.
=> Fix division by zero error when no Swap available

src/rpi-cpu2mqtt.py
fix for reported issue [https://github.com/hjelev/rpi-mqtt-monitor/issues/104](url)
=> Sanitize hostname by replacing illegal topic characters

install.sh
create a shortcut during installation
=> update install script and add shortcut creation

install.sh, rpi-mqtt-monitor.service, src/config.py.example, src/rpi-cpu2mqtt.py
to use this feature you'll need to reinstall or add/update config.py os_user value to your username
=> add monitor control support

src/rpi-cpu2mqtt.py
Added data["device_class"] = "temperature" to align with other temperature values.
=> Device_Class for Temperature added

src/config.py.example, src/rpi-cpu2mqtt.py
Added RPi Power Status Sensor which as the name tells only works on raspberry pis
=> RPi Power Status Sensor

src/config.py.example, src/rpi-cpu2mqtt.py
If you are using `uptime_days = True` you'll have to re-add it to your dashboard.
=> Rename uptime_days to uptime and make it a timestamp

README.md, src/config.py.example
fix broken anchors in README.md and organize config.py
=> house keeping 

src/rpi-cpu2mqtt.py
:: Scheduling
Running as Service
=> display scheduling method in -d output

src/translations.ini
=> Add French translation
